### ISSUE TITLE
Publicar a v0.1 do jogo no gitHub Pages

### ISSUE THREAD

**Issue by PBertotti** [falarya-brawl/falarya-game#15]
Adicionado, acesso habilitado no repositório.

**Comment by gabrielly-cristina** [comment]
A implementação do protocolo WebRTC se deu pela aplicação da funcionalidade de transmissão da mídia de aúdio entre os diferentes clientes através do protocolo.

O desenvolvimento desta na aplicação se deu através das funcionalidades nativas do Javascript no navegador, utilizando a comunicação WebSockets para protocolagem de canditados, requisiçoes e respotas. Também foi utilizado o suporte do ICE-Server da Google na implementação.

**Comment by gabrielly-cristina** [comment]
Após mudança dos repositórios para v1.2, foi necessário revisar a implementação da documentação no gitHub pages. Implementação realizada
