### ISSUE TITLE
Publicar primeira versão experimental do servidor do jogo

### ISSUE THREAD

**Issue by PBertotti** [falarya-brawl/falarya-game#23]

**Comment by gabrielly-cristina** [comment]
Após finalizada a primeira versão do jogo, esta pode ser enviada para ser hospedada no servidor de produção do jogo. O processo consistiu na hospedagem no node-server, aplicação do serviço no servidor NGINX, geração e aplicação do certificado SSL para protocolo HTTPS e DNS.
