### ISSUE TITLE
Publicar v1.0 para desktop

### ISSUE THREAD

**Issue by PBertotti** [falarya-brawl/falarya-game#30]
Versão 1.0 contendo todas as funcionalidades principais da aplicação publicada no repositório, versionada, e hospedada no servidor com a ajuda da @gabrielly-cristina.

**Comment by ghost** [comment]
Falta marcar as tags nos commits correspondentes, conforme os [vídeos da entrega 7](https://www.youtube.com/playlist?list=PLje9mMro7hT2DE6NfFdN-icd9CYqohLuU).
