### ISSUE TITLE
Implementar WebRTC

### ISSUE THREAD

**Issue by PBertotti** [falarya-brawl/falarya-game#34]

**Comment by gabrielly-cristina** [comment]
A implementação do protocolo WebRTC se deu pela aplicação da funcionalidade de transmissão da mídia de aúdio entre os diferentes clientes através do protocolo.

O desenvolvimento desta na aplicação se deu através das funcionalidades nativas do Javascript no navegador, utilizando a comunicação WebSockets para protocolagem de canditados, requisições e respostas. Também foi utilizado o suporte do ICE-Server da Google na implementação.
